apiVersion: v1
kind: Service
metadata:
  name: chat-app
  namespace: ashraful
spec:
  selector:
    app: chat-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001

